# Numpy Questions and Solutions for Practice



1. Write statement to import numpy?
2. Create an Array using numpy?
3. Create an Array of 10 random integers?
4. Create an array if elements from 10-20?
5. Create an array which contains value 5, ten times?
6. Create a one dimensional array and convert that into 3*3 matrix?
7. Create an array and then convert all the even numbers with 0 ?
8. Create a 2D array of size 3*3 but all the elements should be between 0 and 1 ?
9. Perform the following slicing: -/-
  
10. Concatenate 2D array horizontally and vertically?




In [31]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
rand=np.random.randint(1,50,10)
rand

array([41, 24, 11, 42, 32, 33, 13, 38, 20, 27])

In [9]:
np.unique(rand)

array([11, 13, 20, 24, 27, 32, 33, 38, 41, 42])

In [10]:
ar1=np.arange(10,21)
ar1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
times=np.ones(10)*5
times

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [16]:
matrix=np.arange(1,10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
matrix.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
convert=np.arange(1,11)
convert

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
convert[convert%2==0]=0
convert

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [23]:
convert[convert%2==0]


array([0, 0, 0, 0, 0])

In [24]:
con=np.arange(1,16)
con

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
con[con%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [26]:
random1=np.random.rand(9).reshape(3,3)
random1

array([[0.02927751, 0.90084842, 0.06802575],
       [0.15555589, 0.28192883, 0.79326799],
       [0.03700036, 0.78727794, 0.11633481]])

In [27]:
perform=np.arange(1,17).reshape(4,4)
perform

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
perform[1: ,1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [29]:
np.hstack(perform)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [30]:
np.vstack(perform)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])